#!/bin/bash
source ~/.bash_aliases

#check(){
#	for subdomain in `cat .tempSUBTAKE | grep -i ${1}: | awk 'NF>1{print $NF}' | sort -u`; do 
#		jar-subtake-${1} $subdomain | grep "takeover isnt possible" > /dev/null \
#			&& sed -i "/${subdomain}/d" .tempSUBTAKE
#	done
#}

temp=$(mktemp)
input=$(mktemp)
cat /dev/stdin > $input
cat $input | sed 's/^/https:\/\//g' | nuclei subdomain-takeover/detect-all-takeovers.yaml \
	| while read line; do echo "$(echo $line | cut -d ' ' -f 3 | sed 's/\/$//') $(echo $line | cut -d ':' -f 2 | cut -d ']' -f 1)"; done > $temp
#check fastly
#check shopify
#check fly.io
#check unbounce

takeoversQnt=$(cat $temp | wc -l)
if [ ${takeoversQnt} -gt 0 ]; then
	echo -e "\e[92m${takeoversQnt} possible takeovers found\e[0m" >&2
else
	echo -e "\e[90m0 possible takeovers found\e[0m" >&2
fi
cat $temp
rm $temp $input
