#!/bin/bash
source ~/hacktools/.aliases

temp=$(mktemp)
input=$(mktemp); cat /dev/stdin > $input

cat $input | sed 's/^/https:\/\//g' | nuclei subdomain-takeover/detect-all-takeovers.yaml \
	| while read line; do echo "$(echo $line | cut -d ' ' -f 3 | sed 's/\/$//') $(echo $line | cut -d ':' -f 2 | cut -d ']' -f 1)"; done > $temp

takeoversQnt=$(cat $temp | wc -l)
if [ ${takeoversQnt} -gt 0 ]; then
	echo -e "\e[92m${takeoversQnt} possible takeovers found\e[0m" >&2
else
	echo -e "\e[90m0 possible takeovers found\e[0m" >&2
fi

cat $temp
rm $temp $input
